// Save FCM token
export const SAVE_FCM_TOKEN_REQUEST = 'SAVE_FCM_TOKEN_REQUEST';
export const SAVE_FCM_TOKEN_REQUEST_SUCCESS = 'SAVE_FCM_TOKEN_REQUEST_SUCCESS';
export const SAVE_FCM_TOKEN_REQUEST_FAILURE = 'SAVE_FCM_TOKEN_REQUEST_FAILURE';

// Create spot
export const CREATE_SPOT_REQUEST = 'CREATE_SPOT_REQUEST';
export const CREATE_SPOT_REQUEST_SUCCESS = 'CREATE_SPOT_REQUEST_SUCCESS';
export const CREATE_SPOT_REQUEST_FAILURE = 'CREATE_SPOT_REQUEST_FAILURE';

// Get all spots
export const GET_ALL_SPOTS_REQUEST = 'GET_ALL_SPOTS_REQUEST';
export const GET_ALL_SPOTS_REQUEST_SUCCESS = 'GET_ALL_SPOTS_REQUEST_SUCCESS';
export const GET_ALL_SPOTS_REQUEST_FAILURE = 'GET_ALL_SPOTS_REQUEST_FAILURE';

// Get all finders
export const GET_ALL_FINDERS_REQ = 'GET_ALL_FINDERS_REQ';
export const GET_ALL_FINDERS_REQ_SUCCESS = 'GET_ALL_FINDERS_REQ_SUCCESS';
export const GET_ALL_FINDERS_REQ_FAILURE = 'GET_ALL_FINDERS_REQ_FAILURE';

// Activate Spot
export const ACTIVATE_SPOT_REQUEST = 'ACTIVATE_SPOT_REQUEST';
export const ACTIVATE_SPOT_REQUEST_SUCCESS = 'ACTIVATE_SPOT_REQUEST_SUCCESS';
export const ACTIVATE_SPOT_REQUEST_FAILURE = 'ACTIVATE_SPOT_REQUEST_FAILURE';

// Create connection
export const CREATE_CONNECTION_REQ = 'CREATE_CONNECTION_REQ';
export const CREATE_CONNECTION_REQ_SUCCESS = 'CREATE_CONNECTION_REQ_SUCCESS';
export const CREATE_CONNECTION_REQ_FAILURE = 'CREATE_CONNECTION_REQ_FAILURE';

// Cancel connection
export const CANCEL_CONNECTION_REQ = 'CANCEL_CONNECTION_REQ';
export const CANCEL_CONNECTION_REQ_SUCCESS = 'CANCEL_CONNECTION_REQ_SUCCESS';
export const CANCEL_CONNECTION_REQ_FAILURE = 'CANCEL_CONNECTION_REQ_FAILURE';

// Create conversation
export const CREATE_CONVERSATION_REQ = 'CREATE_CONVERSATION_REQ';
export const CREATE_CONVERSATION_REQ_SUCCESS =
  'CREATE_CONVERSATION_REQ_SUCCESS';
export const CREATE_CONVERSATION_REQ_FAILURE =
  'CREATE_CONVERSATION_REQ_FAILURE';

// Get conversations
export const GET_CONVERSATIONS_REQ = 'GET_CONVERSATIONS_REQ';
export const GET_CONVERSATIONS_REQ_SUCCESS = 'GET_CONVERSATIONS_REQ_SUCCESS';
export const GET_CONVERSATIONS_REQ_FAILURE = 'GET_CONVERSATIONS_REQ_FAILURE';

// Delete conversation
export const DELETE_CONVERSATION_REQ = 'DELETE_CONVERSATION_REQ';
export const DELETE_CONVERSATION_REQ_SUCCESS =
  'DELETE_CONVERSATION_REQ_SUCCESS';
export const DELETE_CONVERSATION_REQ_FAILURE =
  'DELETE_CONVERSATION_REQ_FAILURE';

// Bolck/Unblock chat
export const BLOCK_UNBLOCK_CHAT_REQ = 'BLOCK_UNBLOCK_CHAT_REQ';
export const BLOCK_UNBLOCK_CHAT_REQ_SUCCESS = 'BLOCK_UNBLOCK_CHAT_REQ_SUCCESS';
export const BLOCK_UNBLOCK_CHAT_REQ_FAILURE = 'BLOCK_UNBLOCK_CHAT_REQ_FAILURE';

// Get messages
export const GET_MESSAGES_REQUEST = 'GET_MESSAGES_REQUEST';
export const GET_MESSAGES_REQUEST_SUCCESS = 'GET_MESSAGES_REQUEST_SUCCESS';
export const GET_MESSAGES_REQUEST_FAILURE = 'GET_MESSAGES_REQUEST_FAILURE';

// Send message
export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_REQUEST_SUCCESS = 'SEND_MESSAGE_REQUEST_SUCCESS';
export const SEND_MESSAGE_REQUEST_FAILURE = 'SEND_MESSAGE_REQUEST_FAILURE';

// Confirm cancel connection
export const CONFIRM_CANCEL_CONNECTION_REQ = 'CONFIRM_CANCEL_CONNECTION_REQ';
export const CONFIRM_CANCEL_CONNECTION_REQ_SUCCESS =
  'CONFIRM_CANCEL_CONNECTION_REQ_SUCCESS';
export const CONFIRM_CANCEL_CONNECTION_REQ_FAILURE =
  'CONFIRM_CANCEL_CONNECTION_REQ_FAILURE';

// Transfer parking spot
export const TRANSFER_PARKING_SPOT_REQ = 'TRANSFER_PARKING_SPOT_REQ';
export const TRANSFER_PARKING_SPOT_REQ_SUCCESS =
  'TRANSFER_PARKING_SPOT_REQ_SUCCESS';
export const TRANSFER_PARKING_SPOT_REQ_FAILURE =
  'TRANSFER_PARKING_SPOT_REQ_FAILURE';

// Avail parking spot
export const AVAIL_PARKING_SPOT_REQ = 'AVAIL_PARKING_SPOT_REQ';
export const AVAIL_PARKING_SPOT_REQ_SUCCESS = 'AVAIL_PARKING_SPOT_REQ_SUCCESS';
export const AVAIL_PARKING_SPOT_REQ_FAILURE = 'AVAIL_PARKING_SPOT_REQ_FAILURE';

// Confirm arrival
export const CONFIRM_ARRIVAL_REQ = 'CONFIRM_ARRIVAL_REQ';
export const CONFIRM_ARRIVAL_REQ_SUCCESS = 'CONFIRM_ARRIVAL_REQ_SUCCESS';
export const CONFIRM_ARRIVAL_REQ_FAILURE = 'CONFIRM_ARRIVAL_REQ_FAILURE';

// Still interested
export const STILL_INSTERESTED_REQ = 'STILL_INSTERESTED_REQ';
export const STILL_INSTERESTED_REQ_SUCCESS = 'STILL_INSTERESTED_REQ_SUCCESS';
export const STILL_INSTERESTED_REQ_FAILURE = 'STILL_INSTERESTED_REQ_FAILURE';

// Save swapper loc
export const SAVE_SWAPPER_LOC_REQ = 'SAVE_SWAPPER_LOC_REQ';
export const SAVE_SWAPPER_LOC_REQ_SUCCESS = 'SAVE_SWAPPER_LOC_REQ_SUCCESS';
export const SAVE_SWAPPER_LOC_REQ_FAILURE = 'SAVE_SWAPPER_LOC_REQ_FAILURE';
