//Get all cards
export const GET_ALL_CARDS_REQUEST = 'GET_ALL_CARDS_REQUEST';
export const GET_ALL_CARDS_REQUEST_SUCCESS = 'GET_ALL_CARDS_REQUEST_SUCCESS';
export const GET_ALL_CARDS_REQUEST_FAILURE = 'GET_ALL_CARDS_REQUEST_FAILURE';

//add card
export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_REQUEST_SUCCESS = 'ADD_CARD_REQUEST_SUCCESS';
export const ADD_CARD_REQUEST_FAILURE = 'ADD_CARD_REQUEST_FAILURE';

//update card
export const UPDATE_CARD_REQUEST = 'UPDATE_CARD_REQUEST';
export const UPDATE_CARD_REQUEST_SUCCESS = 'UPDATE_CARD_REQUEST_SUCCESS';
export const UPDATE_CARD_REQUEST_FAILURE = 'UPDATE_CARD_REQUEST_FAILURE';

//delete card
export const DELETE_CARD_REQUEST = 'DELETE_CARD_REQUEST';
export const DELETE_CARD_REQUEST_SUCCESS = 'DELETE_CARD_REQUEST_SUCCESS';
export const DELETE_CARD_REQUEST_FAILURE = 'DELETE_CARD_REQUEST_FAILURE';

//get wallet details
export const GET_WALLET_DETAILS_REQ = 'GET_WALLET_DETAILS_REQ';
export const GET_WALLET_DETAILS_REQ_SUCCESS = 'GET_WALLET_DETAILS_REQ_SUCCESS';
export const GET_WALLET_DETAILS_REQ_FAILURE = 'GET_WALLET_DETAILS_REQ_FAILURE';

//get link
export const GET_LINK_REQUEST = 'GET_LINK_REQUEST';
export const GET_LINK_REQUEST_SUCCESS = 'GET_LINK_REQUEST_SUCCESS';
export const GET_LINK_REQUEST_FAILURE = 'GET_LINK_REQUEST_FAILURE';

//top up
export const TOP_UP_REQUEST = 'TOP_UP_REQUEST';
export const TOP_UP_REQUEST_SUCCESS = 'TOP_UP_REQUEST_SUCCESS';
export const TOP_UP_REQUEST_FAILURE = 'TOP_UP_REQUEST_FAILURE';
//withdraw
export const WITH_DRAW_REQUEST = 'WITH_DRAW_REQUEST';
export const WITH_DRAW_REQUEST_SUCCESS = 'WITH_DRAW_REQUEST_SUCCESS';
export const WITH_DRAW_REQUEST_FAILURE = 'WITH_DRAW_REQUEST_FAILURE';

//default pay method up
export const DEFAULT_PAY_METHOD_REQ = 'DEFAULT_PAY_METHOD_REQ';
export const DEFAULT_PAY_METHOD_REQ_SUCCESS = 'DEFAULT_PAY_METHOD_REQ_SUCCESS';
export const DEFAULT_PAY_METHOD_REQ_FAILURE = 'DEFAULT_PAY_METHOD_REQ_FAILURE';

//add paypal account
export const ADD_PAYPAL_ACCOUNT_REQ = 'ADD_PAYPAL_ACCOUNT_REQ';
export const ADD_PAYPAL_ACCOUNT_REQ_SUCCESS = 'ADD_PAYPAL_ACCOUNT_REQ_SUCCESS';
export const ADD_PAYPAL_ACCOUNT_REQ_FAILURE = 'ADD_PAYPAL_ACCOUNT_REQ_FAILURE';

//save paypal account
export const SAVE_PAYPAL_ACCOUNT_REQ = 'SAVE_PAYPAL_ACCOUNT_REQ';
export const SAVE_PAYPAL_ACCOUNT_REQ_SUCCESS =
  'SAVE_PAYPAL_ACCOUNT_REQ_SUCCESS';
export const SAVE_PAYPAL_ACCOUNT_REQ_FAILURE =
  'SAVE_PAYPAL_ACCOUNT_REQ_FAILURE';

//get approval url
export const GET_APPROVAL_URL_REQ = 'GET_APPROVAL_URL_REQ';
export const GET_APPROVAL_URL_REQ_SUCCESS = 'GET_APPROVAL_URL_REQ_SUCCESS';
export const GET_APPROVAL_URL_REQ_FAILURE = 'GET_APPROVAL_URL_REQ_FAILURE';

//save paypal res
export const SAVE_PAYPAL_RES_REQ = 'SAVE_PAYPAL_RES_REQ';
export const SAVE_PAYPAL_RES_REQ_SUCCESS = 'SAVE_PAYPAL_RES_REQ_SUCCESS';
export const SAVE_PAYPAL_RES_REQ_FAILURE = 'SAVE_PAYPAL_RES_REQ_FAILURE';
