//Get profile
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_REQUEST_SUCCESS = 'GET_PROFILE_REQUEST_SUCCESS';
export const GET_PROFILE_REQUEST_FAILURE = 'GET_PROFILE_REQUEST_FAILURE';

//Update profile
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_REQUEST_SUCCESS = 'UPDATE_PROFILE_REQUEST_SUCCESS';
export const UPDATE_PROFILE_REQUEST_FAILURE = 'UPDATE_PROFILE_REQUEST_FAILURE';

//Get car info
export const GET_CAR_INFO_REQUEST = 'GET_CAR_INFO_REQUEST';
export const GET_CAR_INFO_REQUEST_SUCCESS = 'GET_CAR_INFO_REQUEST_SUCCESS';
export const GET_CAR_INFO_REQUEST_FAILURE = 'GET_CAR_INFO_REQUEST_FAILURE';

//Update car info
export const UPADTE_CAR_INFO_REQUEST = 'UPADTE_CAR_INFO_REQUEST';
export const UPADTE_CAR_INFO_REQUEST_SUCCESS =
  'UPADTE_CAR_INFO_REQUEST_SUCCESS';
export const UPADTE_CAR_INFO_REQUEST_FAILURE =
  'UPADTE_CAR_INFO_REQUEST_FAILURE';

//Get quick chats
export const GET_QUICK_CHATS_REQUEST = 'GET_QUICK_CHATS_REQUEST';
export const GET_QUICK_CHATS_REQUEST_SUCCESS =
  'GET_QUICK_CHATS_REQUEST_SUCCESS';
export const GET_QUICK_CHATS_REQUEST_FAILURE =
  'GET_QUICK_CHATS_REQUEST_FAILURE';

//Add quick chat
export const ADD_QUICK_CHAT_REQUEST = 'ADD_QUICK_CHAT_REQUEST';
export const ADD_QUICK_CHAT_REQUEST_SUCCESS = 'ADD_QUICK_CHAT_REQUEST_SUCCESS';
export const ADD_QUICK_CHAT_REQUEST_FAILURE = 'ADD_QUICK_CHAT_REQUEST_FAILURE';

//Edit quick chat
export const EDIT_QUICK_CHAT_REQUEST = 'EDIT_QUICK_CHAT_REQUEST';
export const EDIT_QUICK_CHAT_REQUEST_SUCCESS =
  'EDIT_QUICK_CHAT_REQUEST_SUCCESS';
export const EDIT_QUICK_CHAT_REQUEST_FAILURE =
  'EDIT_QUICK_CHAT_REQUEST_FAILURE';

//Remove quick chat
export const REMOVE_QUICK_CHAT_REQUEST = 'REMOVE_QUICK_CHAT_REQUEST';
export const REMOVE_QUICK_CHAT_REQUEST_SUCCESS =
  'REMOVE_QUICK_CHAT_REQUEST_SUCCESS';
export const REMOVE_QUICK_CHAT_REQUEST_FAILURE =
  'REMOVE_QUICK_CHAT_REQUEST_FAILURE';

//Static pages
export const STATIC_PAGES_REQUEST = 'STATIC_PAGES_REQUEST';
export const STATIC_PAGES_SUCCESS = 'STATIC_PAGES_SUCCESS';
export const STATIC_PAGES_FAILURE = 'STATIC_PAGES_FAILURE';

//Get FAQs
export const GET_FAQS_REQUEST = 'GET_FAQS_REQUEST';
export const GET_FAQS_SUCCESS = 'GET_FAQS_SUCCESS';
export const GET_FAQS_FAILURE = 'GET_FAQS_FAILURE';

//Get support tickets
export const GET_SUPPORT_TICKETS_REQUEST = 'GET_SUPPORT_TICKETS_REQUEST';
export const GET_SUPPORT_TICKETS_SUCCESS = 'GET_SUPPORT_TICKETS_SUCCESS';
export const GET_SUPPORT_TICKETS_FAILURE = 'GET_SUPPORT_TICKETS_FAILURE';

//Create support ticket
export const CREATE_SUPPORT_TICKETS_REQUEST = 'CREATE_SUPPORT_TICKETS_REQUEST';
export const CREATE_SUPPORT_TICKETS_SUCCESS = 'CREATE_SUPPORT_TICKETS_SUCCESS';
export const CREATE_SUPPORT_TICKETS_FAILURE = 'CREATE_SUPPORT_TICKETS_FAILURE';

//Get support messages
export const GET_SUPPORT_MESSAGES_REQUEST = 'GET_SUPPORT_MESSAGES_REQUEST';
export const GET_SUPPORT_MESSAGES_SUCCESS = 'GET_SUPPORT_MESSAGES_SUCCESS';
export const GET_SUPPORT_MESSAGES_FAILURE = 'GET_SUPPORT_MESSAGES_FAILURE';

//Send support message
export const SEND_SUPPORT_MESSAGE_REQUEST = 'SEND_SUPPORT_MESSAGE_REQUEST';
export const SEND_SUPPORT_MESSAGE_SUCCESS = 'SEND_SUPPORT_MESSAGE_SUCCESS';
export const SEND_SUPPORT_MESSAGE_FAILURE = 'SEND_SUPPORT_MESSAGE_FAILURE';

//Get history
export const GET_HISTORY_REQUEST = 'GET_HISTORY_REQUEST';
export const GET_HISTORY_REQUEST_SUCCESS = 'GET_HISTORY_REQUEST_SUCCESS';
export const GET_HISTORY_REQUEST_FAILURE = 'GET_HISTORY_REQUEST_FAILURE';

//Toggle online status
export const TOGGLE_ONLINE_STATUS_REQ = 'TOGGLE_ONLINE_STATUS_REQ';
export const TOGGLE_ONLINE_STATUS_REQ_SUCCESS =
  'TOGGLE_ONLINE_STATUS_REQ_SUCCESS';
export const TOGGLE_ONLINE_STATUS_REQ_FAILURE =
  'TOGGLE_ONLINE_STATUS_REQ_FAILURE';
