-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHueCw+tFUJ222Ytp
EktPU7EXcIn/yM7Mv7lbbbRHJHWgCgYIKoZIzj0DAQehRANCAAR8TyPoYy1YpH7W
9GB3dkJmd4xxJtBeRSBWmYX2NvFlxbomAGDTc2GXFVeGgCs9W2lkULaG5f9RNcx6
q+Lo/Vg/
-----END PRIVATE KEY-----